"""add chat message model

Revision ID: 1476dcd6ed1c
Revises: 8e54c990a613
Create Date: 2025-12-22 23:01:03.924096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1476dcd6ed1c'
down_revision = '8e54c990a613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
