"""add chat message model

Revision ID: 1b370a92f60a
Revises: 9d06b5922574
Create Date: 2025-12-22 23:10:09.766809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b370a92f60a'
down_revision = '9d06b5922574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
