"""add chat message model

Revision ID: 253cd55d62a5
Revises: 7103a0bc1f89
Create Date: 2025-12-23 21:35:04.408748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253cd55d62a5'
down_revision = '7103a0bc1f89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
