"""add chat message model

Revision ID: 7103a0bc1f89
Revises: 829dc8bbd1f2
Create Date: 2025-12-23 20:45:14.101705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7103a0bc1f89'
down_revision = '829dc8bbd1f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
