"""add core feature models

Revision ID: 829dc8bbd1f2
Revises: 1b370a92f60a
Create Date: 2025-12-23 20:36:46.753661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829dc8bbd1f2'
down_revision = '1b370a92f60a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_request_id', sa.Integer(), nullable=True))
        batch_op.alter_column('complaint_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('fk_chat_message_service_request', 'service_request', ['service_request_id'], ['id'])

    with op.batch_alter_table('service_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('review', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_average', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rating_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('rating_count')
        batch_op.drop_column('rating_average')

    with op.batch_alter_table('service_request', schema=None) as batch_op:
        batch_op.drop_column('completed_at')
        batch_op.drop_column('review')
        batch_op.drop_column('rating')

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('complaint_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('service_request_id')

    # ### end Alembic commands ###
