"""add chat message model

Revision ID: 8d30027d01c1
Revises: d79d73423338
Create Date: 2025-12-24 22:49:46.674483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d30027d01c1'
down_revision = 'd79d73423338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
