"""add premium fields

Revision ID: 9d06b5922574
Revises: 1476dcd6ed1c
Create Date: 2025-12-22 23:06:07.563686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d06b5922574'
down_revision = '1476dcd6ed1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_premium', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('subscription_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('subscription_expiry')
        batch_op.drop_column('is_premium')

    # ### end Alembic commands ###
