"""add chat message model

Revision ID: d3e1a4c30a86
Revises: 253cd55d62a5
Create Date: 2025-12-23 21:44:12.464175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e1a4c30a86'
down_revision = '253cd55d62a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
