"""add chat message model

Revision ID: d79d73423338
Revises: d3e1a4c30a86
Create Date: 2025-12-23 21:50:04.876205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd79d73423338'
down_revision = 'd3e1a4c30a86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
